package com.project.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_attach", "id", TAttach.class);
		arp.addMapping("t_contents", "id", TContents.class);
		arp.addMapping("t_contents_type", "id", TContentsType.class);
		arp.addMapping("t_information", "id", TInformation.class);
		arp.addMapping("t_information_type", "id", TInformationType.class);
		arp.addMapping("t_log", "id", TLog.class);
		arp.addMapping("t_products", "id", TProducts.class);
		arp.addMapping("t_products_type", "id", TProductsType.class);
		arp.addMapping("t_user", "id", TUser.class);
		arp.addMapping("t_contact_us", "id", TContactUs.class);
	}
}

