package com.project.model;

import com.project.model.base.BaseTAttach;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TAttach extends BaseTAttach<TAttach> {
	public static final TAttach dao = new TAttach().dao();
}
