package com.project.model;

import com.project.model.base.BaseTContactUs;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TContactUs extends BaseTContactUs<TContactUs> {
	public static final TContactUs dao = new TContactUs().dao();
}
