package com.project.model;

import com.project.model.base.BaseTContentsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TContentsType extends BaseTContentsType<TContentsType> {
	public static final TContentsType dao = new TContentsType().dao();
}
