package com.project.model;

import com.project.model.base.BaseTContents;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TContents extends BaseTContents<TContents> {
	public static final TContents dao = new TContents().dao();
}
