package com.project.model;

import com.project.model.base.BaseTInformationType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TInformationType extends BaseTInformationType<TInformationType> {
	public static final TInformationType dao = new TInformationType().dao();
}
