package com.project.model;

import com.project.model.base.BaseTInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TInformation extends BaseTInformation<TInformation> {
	public static final TInformation dao = new TInformation().dao();
}
