package com.project.model;

import com.project.model.base.BaseTProducts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TProducts extends BaseTProducts<TProducts> {
	public static final TProducts dao = new TProducts().dao();
}
