package com.project.model;

import com.project.model.base.BaseTProductsType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TProductsType extends BaseTProductsType<TProductsType> {
	public static final TProductsType dao = new TProductsType().dao();
}
