package com.project.model;

import com.project.model.base.BaseTUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TUser extends BaseTUser<TUser> {
	public static final TUser dao = new TUser().dao();
}
