package com.project.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTUser<M extends BaseTUser<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}

	public java.lang.Integer getID() {
		return get("ID");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return get("mobile");
	}

	public void setRegTime(java.util.Date regTime) {
		set("reg_time", regTime);
	}

	public java.util.Date getRegTime() {
		return get("reg_time");
	}

	public void setUserType(java.lang.String userType) {
		set("user_type", userType);
	}

	public java.lang.String getUserType() {
		return get("user_type");
	}

	public void setModifyUse(java.lang.Integer modifyUse) {
		set("modify_use", modifyUse);
	}

	public java.lang.Integer getModifyUse() {
		return get("modify_use");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

}
