package com.project.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTInformationType<M extends BaseTInformationType<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setInformationCode(java.lang.String informationCode) {
		set("information_code", informationCode);
	}

	public java.lang.String getInformationCode() {
		return get("information_code");
	}

	public void setInformationName(java.lang.String informationName) {
		set("information_name", informationName);
	}

	public java.lang.String getInformationName() {
		return get("information_name");
	}
	

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

}
