package com.project.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTLog<M extends BaseTLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setModelId(byte[] modelId) {
		set("model_ID", modelId);
	}

	public byte[] getModelId() {
		return get("model_ID");
	}

	public void setRelId(byte[] relId) {
		set("rel_id", relId);
	}

	public byte[] getRelId() {
		return get("rel_id");
	}

	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

	public java.lang.String getRemarks() {
		return get("remarks");
	}

	public void setCreateUse(java.lang.String createUse) {
		set("create_use", createUse);
	}

	public java.lang.String getCreateUse() {
		return get("create_use");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

}
