package com.project.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTAttach<M extends BaseTAttach<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setModelId(byte[] modelId) {
		set("model_ID", modelId);
	}

	public byte[] getModelId() {
		return get("model_ID");
	}

	public void setRelId(byte[] relId) {
		set("rel_id", relId);
	}

	public byte[] getRelId() {
		return get("rel_id");
	}

	public void setPathFile(byte[] pathFile) {
		set("path_file", pathFile);
	}

	public byte[] getPathFile() {
		return get("path_file");
	}

	public void setMenuOrder(java.lang.Integer menuOrder) {
		set("menu_order", menuOrder);
	}

	public java.lang.Integer getMenuOrder() {
		return get("menu_order");
	}

	public void setCreateUse(java.lang.String createUse) {
		set("create_use", createUse);
	}

	public java.lang.String getCreateUse() {
		return get("create_use");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyUse(java.lang.String modifyUse) {
		set("modify_use", modifyUse);
	}

	public java.lang.String getModifyUse() {
		return get("modify_use");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
