package com.project.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTContents<M extends BaseTContents<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPostTitle(java.lang.String postTitle) {
		set("post_title", postTitle);
	}

	public java.lang.String getPostTitle() {
		return get("post_title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setExcerpt(java.lang.String excerpt) {
		set("excerpt", excerpt);
	}

	public java.lang.String getExcerpt() {
		return get("excerpt");
	}

	public void setPostDate(java.util.Date postDate) {
		set("post_date", postDate);
	}

	public java.util.Date getPostDate() {
		return get("post_date");
	}

	public void setMenuOrder(java.lang.Integer menuOrder) {
		set("menu_order", menuOrder);
	}

	public java.lang.Integer getMenuOrder() {
		return get("menu_order");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setBrowseNum(java.lang.Integer browseNum) {
		set("browse_num", browseNum);
	}

	public java.lang.Integer getBrowseNum() {
		return get("browse_num");
	}

	public void setCreateUse(java.lang.String createUse) {
		set("create_use", createUse);
	}

	public java.lang.String getCreateUse() {
		return get("create_use");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setModifyUse(java.lang.String modifyUse) {
		set("modify_use", modifyUse);
	}

	public java.lang.String getModifyUse() {
		return get("modify_use");
	}

	public void setModifyDate(java.util.Date modifyDate) {
		set("modify_date", modifyDate);
	}

	public java.util.Date getModifyDate() {
		return get("modify_date");
	}

}
